using UnityEngine;

public class Guillotine : MonoBehaviour
{

    public float fuerza = 300f;        // fuerza del motor
    public float velocidadMax = 100f;  // velocidad m치xima de oscilaci칩n
    public float frecuencia = 2f;      // cu치ntas veces por segundo cambia de direcci칩n
    private HingeJoint hinge;
    JointMotor motor;
    void Start()
    {
        hinge = GetComponent<HingeJoint>();
        hinge.useMotor = true;
        motor = hinge.motor;
        motor.force = fuerza;
    }
    void FixedUpdate()
    {
        float velocidad = Mathf.Sin(Time.time * frecuencia) * velocidadMax;
        motor.targetVelocity = velocidad;
        hinge.motor = motor;
    }
}





